khs/internet_check/urls.py
from django.urls import path

from . import views

app_name = 'internet_check'

urlpatterns = [
    path('', views.index, name='index'),
    path('api/internet_speed', views.api_internet_speed),
    path('api/internet_status', views.api_internet_status)
]

khs/khs/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = 'khs'

urlpatterns = [
    path('', views.indexx, name='index'),
    path('internet_check/',
         include('internet_check.urls', namespace='internet_check'),
         name='internet_check'),
    path('admin/', admin.site.urls, name='admin'),
]

khs/internet_check/models.py
from django.db import models

# Create your models here.


class InternetStatus(models.Model):
    change_time = models.DateTimeField()
    status = models.BooleanField()


class InternetSpeed(models.Model):
    date = models.DateTimeField()
    upload = models.FloatField()
    download = models.FloatField()

khs/internet_check/views.py
from django.http import HttpResponse
from django.template import loader
from django.core import serializers
from .models import InternetSpeed, InternetStatus
# Main


def index(request):
    template = loader.get_template('internet_check/base.html')
    return HttpResponse(template.render())


# API


def api_internet_speed(_):
    internet_speed = serializers.serialize(
        "json", InternetSpeed.objects.order_by('-date'))
    return HttpResponse(internet_speed)


def api_internet_status(_):
    internet_status = serializers.serialize(
        "json", InternetStatus.objects.all())
    return HttpResponse(internet_status)

khs/khs/views.py
from django.http import HttpResponse
from django.template import loader


def indexx(request):
    template = loader.get_template('khs/base.html')

    return HttpResponse(template.render())

khs/internet_check/templates/internet_check/base.html
{% extends 'khs/base.html' %}
{% block body %}
{% load static %}
<script type="text/javascript" src="{% static 'internet_check/internet_check.js' %}"></script>

<table class="table">
    <tr>
        <td>
            <h1>Internet Check</h1>
        </td>
        <td class="text-right">
            <h2 id="current_time"></h2>
        </td>
    </tr>

</table>
<div class="alert alert-success" role="alert" id="main_msg">
    Current status: <span id="current_status">OK!</span> <span id="emoji"><svg class="bi bi-emoji-laughing" width="2em"
            height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
            <path fill-rule="evenodd"
                d="M12.331 9.5a1 1 0 0 1 0 1A4.998 4.998 0 0 1 8 13a4.998 4.998 0 0 1-4.33-2.5A1 1 0 0 1 4.535 9h6.93a1 1 0 0 1 .866.5z" />
            <path
                d="M7 6.5c0 .828-.448 0-1 0s-1 .828-1 0S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 0-1 0s-1 .828-1 0S9.448 5 10 5s1 .672 1 1.5z" />
        </svg></span>
    <div id="current_length_msg"></div>
    <div id>Last check: <b id="last_time"></b></div>
    <div id="last_speed" class="visible" updated="false">Download: <b id="last_download">0 Mb/s</b>, Upload: <b
            id="last_upload">0
            Mb/s</b></div>
    <div id="duration_msg" class="visible"></div>
</div>

<div class="progress" onclick="icMain.clickProgressBar()">
    <div id="autorefresh_bar" data_time="0" data_refresh='true'
        class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 100%"
        aria-valuenow="10" aria-valuemin="0" aria-valuemax="300"></div>
</div>

{% include 'internet_check/internet_speed.html' %}


<div class=" accordion" id="accordionExample">

    <div class="card">
        <div class="card-header" id="headingTwo">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="false" aria-controls="collapseTwo">
                    Internet status
                </button>
            </h5>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
            <div class="card-body">

                {% include 'internet_check/internet_status.html' %}


            </div>
        </div>
    </div>
</div>
{% endblock %}

khs/internet_check/templates/internet_check/internet_speed.html
<div id="myChart" style="position: relative; height:35vh; width: 95%"></canvas>
</div>
<table class="table table-responsive" id="speed_table">
    <thead>
        <th scope="col">#</th>
        <th scope="col">Max download</th>
        <th scope="col">Avg download</th>
        <th scope="col">Max upload</th>
        <th scope="col">Avg upload</th>
        <th scope="col">Days</th>
        <th scope="col">hours</th>
        <th scope="col">minutes</th>
        <th scope="col">Days</th>
        <th scope="col">hours</th>
        <th scope="col">minutes</th>
    </thead>
    <tbody>
    </tbody>
</table>

khs/internet_check/templates/internet_check/internet_status.html
<table class="table table-responsive" id="status_table">
    <thead>
        <th scope="col">From</th>
        <th scope="col">To</th>
        <th scope="col">Status</th>
        <th scope="col">Days</th>
        <th scope="col">Hours</th>
        <th scope="col">Minutes</th>
    </thead>
    <tbody>
    </tbody>
</table>

khs/khs/templates/khs/base.html
<html>


<head>{% include 'khs/js.html' %}

</head>

<body>
    {% include 'khs/navbar.html' %}
    {% block body %} {% endblock %}
</body>

</html>

khs/khs/templates/khs/js.html
{% load static %}

<!-- JQUERY -->
<script type="text/javascript" src="{% static 'node_modules/jquery/dist/jquery.js' %}"></script>

<!-- BOOTSTRAP -->
<script type="text/javascript" src="{% static 'node_modules/bootstrap/dist/js/bootstrap.js' %}"></script>

<link rel="stylesheet" href="{% static 'khs/ccolors.css' %}">
<link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'node_modules/bootswatch/dist/darkly/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'khs/darkly.css' %}">

<!-- MOMENT -->
<script type="text/javascript" src="{% static 'node_modules/moment/moment.js' %}"></script>
<script>
    moment().format();
</script>

<!-- CHARTS -->
<script type="text/javascript" src="{% static 'node_modules/dygraphs/dist/dygraph.js' %}"></script>

<!-- TABLESORTER -->
<script type="text/javascript" src="{% static 'node_modules/tablesorter/dist/js/jquery.tablesorter.js' %}"></script>
<script type="text/javascript"
    src="{% static 'node_modules/tablesorter/dist/js/widgets/widget-math.min.js' %}"></script>

<!-- CUSTOM -->
<script type="text/javascript" src="{% static 'common/common.js' %}"></script>

khs/khs/templates/khs/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">K-Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin<span class="sr-only"></span></a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'internet_check:index' %}">Internet Check<span
                        class="sr-only"></span></a>
            </li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="pull-right">

                <button class="btn btn-dark" type="submit" onClick="DarkTheme.change()"><svg class="bi bi-moon"
                        width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M14.53 10.53a7 7 0 0 1-9.058-9.058A7.003 7.003 0 0 0 8 15a7.002 7.002 0 0 0 6.53-4.47z" />
                    </svg></button>
            </li>
        </ul>
    </div>
</nav>